function initLogbookUI() {
    renderEventsList(); renderMotorenList(); renderAutosList(); renderStreckenList();

    const bindBtn = (id, fn) => { const btn = document.getElementById(id); if(btn) btn.addEventListener('click', fn); };
    
    bindBtn('addEventButton', ()=>showEventsModal());
    bindBtn('addAutoButton', ()=>{document.getElementById('autosForm').reset();document.getElementById('autoIdInput').value='';document.getElementById('autosModalTitle').textContent='Neues Auto';document.getElementById('autosModal').style.display='flex';});
    bindBtn('addMotorButton', ()=>showMotorenModal());
    bindBtn('addStreckeButton', ()=>{document.getElementById('streckenForm').reset();document.getElementById('streckeIdInput').value='';document.getElementById('streckenModalTitle').textContent='Neue Strecke';document.getElementById('streckenModal').style.display='flex';});

    bindBtn('cancelEventButton', () => document.getElementById('eventsModal').style.display = 'none');
    bindBtn('cancelAutoButton', () => document.getElementById('autosModal').style.display = 'none');
    bindBtn('cancelMotorButton', () => document.getElementById('motorenModal').style.display = 'none');
    bindBtn('cancelStreckeButton', () => document.getElementById('streckenModal').style.display = 'none');

    setupTbl('eventsTbody', showEventsModal, 'events'); 
    setupTbl('motorenTbody', showMotorenModal, 'motoren');
    setupTbl('autosTbody', (id)=>{showAutosModal(id)}, 'autos');
    setupTbl('streckenTbody', (id)=>{showStreckenModal(id)}, 'strecken');
}

const setupTbl = (id, showFn, list) => {
    const el = document.getElementById(id);
    if(!el) return;
    el.addEventListener('click', e=>{
        const ed=e.target.closest('.edit-btn'); if(ed) showFn(ed.dataset.id);
        const del=e.target.closest('.del-btn'); if(del&&confirm("Löschen?")){ rsDb[list]=rsDb[list].filter(x=>x.id!==del.dataset.id); saveDatabase(); 
            if(list==='events') renderEventsList();
            if(list==='motoren') renderMotorenList();
            if(list==='autos') renderAutosList();
            if(list==='strecken') renderStreckenList();
        }
    });
};

function renderEventsList() {
    const tb = document.getElementById('eventsTbody'); if(!tb) return; tb.innerHTML='';
    const f = document.getElementById('eventSearchInput').value.toLowerCase();
    rsDb.events.filter(e=>!f||Object.values(e).some(v=>String(v).toLowerCase().includes(f))).forEach(e=>{
        tb.innerHTML+=`<tr><td>${formatDateShort(e.datum)}</td><td>${e.klasse||'-'}</td><td>${getStreckeNameById(e.strecke)}</td><td>${e.platz||'-'}</td><td>${e.besteRunde||'-'}</td><td>${e.runden||'-'}</td><td>${getAutoBodyById(e.fahrzeug)}</td><td>${e.reifen||'-'}</td><td>${getMotorNameById(e.motor)}</td><td><div class="logbook-table-actions"><button class="edit-btn text-blue-400" data-id="${e.id}">${ICON_EDIT}</button><button class="del-btn text-red-400" data-id="${e.id}">${ICON_TRASH}</button></div></td></tr>`;
    });
}
// ... (Restliche Render-Funktionen bleiben identisch zu vorherigen Versionen) ...
function renderMotorenList() { const tb = document.getElementById('motorenTbody'); if(!tb)return; tb.innerHTML=''; const f = document.getElementById('motorSearchInput').value.toLowerCase(); rsDb.motoren.filter(m=>!f||Object.values(m).some(v=>String(v).toLowerCase().includes(f))).forEach(m=>{ tb.innerHTML+=`<tr><td>${m.name}</td><td>${m.klasse||'-'}</td><td>${m.hersteller||'-'}</td><td>${m.rpm||'-'}</td><td>${m.maxRpm||'-'}</td><td>${m.rennen||'-'}</td><td>${m.status}</td><td><div class="logbook-table-actions"><button class="edit-btn text-blue-400" data-id="${m.id}">${ICON_EDIT}</button><button class="del-btn text-red-400" data-id="${m.id}">${ICON_TRASH}</button></div></td></tr>`; }); }
function renderAutosList() { const tb = document.getElementById('autosTbody'); if(!tb)return; tb.innerHTML=''; rsDb.autos.forEach(a=>{ tb.innerHTML+=`<tr><td>${a.klasse}</td><td>${a.chassis}</td><td>${a.karosserie}</td><td>${a.motor}</td><td>${a.zahnrad}</td><td>${a.federn}</td><td>${a.wackel}</td><td>${a.gewichtsver}</td><td>${a.kugellager}</td><td>${a.hoehe}</td><td>${a.reifen}</td><td><div class="logbook-table-actions"><button class="edit-btn text-blue-400" data-id="${a.id}">${ICON_EDIT}</button><button class="del-btn text-red-400" data-id="${a.id}">${ICON_TRASH}</button></div></td></tr>`; }); }
function renderStreckenList() { const tb = document.getElementById('streckenTbody'); if(!tb)return; tb.innerHTML=''; rsDb.strecken.forEach(s=>{ tb.innerHTML+=`<tr><td>${s.name}</td><td>${s.ort}</td><td>${s.laenge}</td><td>${s.typ}</td><td>${s.spannung}</td><td>${s.rekord}</td><td>${s.rollout}</td><td><div class="logbook-table-actions"><button class="edit-btn text-blue-400" data-id="${s.id}">${ICON_EDIT}</button><button class="del-btn text-red-400" data-id="${s.id}">${ICON_TRASH}</button></div></td></tr>`; }); }

function sortTable(type, field) { if(currentSort.type===type && currentSort.field===field) currentSort.dir=currentSort.dir==='asc'?'desc':'asc'; else currentSort={type,field,dir:'asc'}; rsDb[type].sort((a,b)=>{ let vA=a[field], vB=b[field]; if(field==='strecke') { vA=getStreckeNameById(a.strecke); vB=getStreckeNameById(b.strecke); } if(vA==null)vA=""; if(vB==null)vB=""; const isNum = !isNaN(parseFloat(vA)) && isFinite(vA); return isNum ? (currentSort.dir==='asc'?vA-vB:vB-vA) : (currentSort.dir==='asc'?String(vA).localeCompare(String(vB)):String(vB).localeCompare(String(vA))); }); if(type==='events') renderEventsList(); else renderMotorenList(); }

function popSel(el,man,items,key,lbl){if(!el)return; el.innerHTML=`<option value="">${lbl}</option>`;items.forEach(i=>{let t=i[key];if(key==='motor')t=`${i.name} (${i.klasse})`;if(key==='auto')t=`${i.klasse}-${i.karosserie}`;el.innerHTML+=`<option value="${i.id}">${t}</option>`});el.innerHTML+='<option value="manual">-- Manuell --</option>';el.onchange=()=>{man.classList.toggle('hidden',el.value!=='manual');};}
function setSelectOrManual(selId, manId, val) { const sel = document.getElementById(selId); const man = document.getElementById(manId); if(!sel) return; let exists = false; for (let i = 0; i < sel.options.length; i++) { if (sel.options[i].value === val) exists = true; } if (exists) { sel.value = val; man.classList.add('hidden'); } else if (val) { sel.value = 'manual'; man.value = val; man.classList.remove('hidden'); } else { sel.value = ''; man.classList.add('hidden'); } }

function showEventsModal(id){ document.getElementById('eventsForm').reset(); ['eventStreckeManuell','eventFahrzeugManuell','eventMotorManuell'].forEach(x=>document.getElementById(x).classList.add('hidden')); popSel(document.getElementById('eventStrecke'),document.getElementById('eventStreckeManuell'),rsDb.strecken,'name','Strecke...'); popSel(document.getElementById('eventFahrzeug'),document.getElementById('eventFahrzeugManuell'),rsDb.autos,'auto','Auto...'); popSel(document.getElementById('eventMotor'),document.getElementById('eventMotorManuell'),rsDb.motoren,'motor','Motor...'); document.getElementById('eventsModalTitle').textContent = id ? 'Event bearbeiten' : 'Neues Event'; if(id){ const e=rsDb.events.find(x=>x.id===id); if(e){ document.getElementById('eventIdInput').value=e.id; document.getElementById('eventDatum').value=e.datum; document.getElementById('eventKlasse').value=e.klasse; setSelectOrManual('eventStrecke', 'eventStreckeManuell', e.strecke); setSelectOrManual('eventFahrzeug', 'eventFahrzeugManuell', e.fahrzeug); setSelectOrManual('eventMotor', 'eventMotorManuell', e.motor); document.getElementById('eventGetriebe').value = e.getriebe||''; document.getElementById('eventReifen').value = e.reifen||''; document.getElementById('eventFedern').value = e.federn||''; document.getElementById('eventWackel').value = e.wackel||''; document.getElementById('eventGewicht').value = e.gewicht||''; document.getElementById('eventQuali').value = e.quali||''; document.getElementById('eventBesteRunde').value = e.besteRunde||''; document.getElementById('eventPlatz').value = e.platz||''; document.getElementById('eventRennzeit').value = e.rennzeit||''; document.getElementById('eventRunden').value = e.runden||''; document.getElementById('eventKommentare').value = e.kommentare||''; } } else { document.getElementById('eventIdInput').value=''; document.getElementById('eventDatum').valueAsDate=new Date(); } document.getElementById('eventsModal').style.display='flex'; }
function showMotorenModal(id){ document.getElementById('motorenForm').reset(); document.getElementById('motorenModalTitle').textContent = id ? 'Motor bearbeiten' : 'Neuer Motor'; if(id){ const m=rsDb.motoren.find(x=>x.id===id); if(m){ document.getElementById('motorIdInput').value=m.id; document.getElementById('motorName').value=m.name; document.getElementById('motorKlasse').value=m.klasse; document.getElementById('motorHersteller').value=m.hersteller; document.getElementById('motorStatus').value=m.status; document.getElementById('motorRpm').value=m.rpm; document.getElementById('motorMaxRpm').value=m.maxRpm; document.getElementById('motorRennen').value=m.rennen; document.getElementById('motorNotizen').value=m.notizen; } } else document.getElementById('motorIdInput').value=''; document.getElementById('motorenModal').style.display='flex'; }
function showAutosModal(id) { document.getElementById('autosForm').reset(); document.getElementById('autosModalTitle').textContent = id ? 'Auto bearbeiten' : 'Neues Auto'; if(id) { const a = rsDb.autos.find(x=>x.id===id); if(a) { document.getElementById('autoIdInput').value=a.id; document.getElementById('autoKlasse').value=a.klasse; document.getElementById('autoChassis').value=a.chassis; document.getElementById('autoKarosserie').value=a.karosserie; document.getElementById('autoFedern').value=a.federn; document.getElementById('autoWackel').value=a.wackel; document.getElementById('autoGewichtsver').value=a.gewichtsver; document.getElementById('autoKugellager').value=a.kugellager; document.getElementById('autoHoehe').value=a.hoehe; document.getElementById('autoReifen').value=a.reifen; document.getElementById('autoMotor').value=a.motor; document.getElementById('autoZahnrad').value=a.zahnrad; document.getElementById('autoKommentare').value=a.kommentare; } } else document.getElementById('autoIdInput').value=''; document.getElementById('autosModal').style.display='flex'; }
function showStreckenModal(id) { document.getElementById('streckenForm').reset(); document.getElementById('streckenModalTitle').textContent = id ? 'Strecke bearbeiten' : 'Neue Strecke'; if(id) { const s = rsDb.strecken.find(x=>x.id===id); if(s) { document.getElementById('streckeIdInput').value=s.id; document.getElementById('streckeName').value=s.name; document.getElementById('streckeOrt').value=s.ort; document.getElementById('streckeLaenge').value=s.laenge; document.getElementById('streckeTyp').value=s.typ; document.getElementById('streckeSpannung').value=s.spannung; document.getElementById('streckeRekord').value=s.rekord; document.getElementById('streckeRollout').value=s.rollout; document.getElementById('streckeNotizen').value=s.notizen; } } else document.getElementById('streckeIdInput').value=''; document.getElementById('streckenModal').style.display='flex'; }

document.addEventListener('DOMContentLoaded', () => {
    const ef = document.getElementById('eventsForm'); if(ef) ef.onsubmit=(e)=>{e.preventDefault();const id=document.getElementById('eventIdInput').value;const d={id:id||`event_${Date.now()}`,datum:document.getElementById('eventDatum').value,klasse:document.getElementById('eventKlasse').value,strecke:document.getElementById('eventStrecke').value==='manual'?document.getElementById('eventStreckeManuell').value:document.getElementById('eventStrecke').value,fahrzeug:document.getElementById('eventFahrzeug').value==='manual'?document.getElementById('eventFahrzeugManuell').value:document.getElementById('eventFahrzeug').value,motor:document.getElementById('eventMotor').value==='manual'?document.getElementById('eventMotorManuell').value:document.getElementById('eventMotor').value,platz:document.getElementById('eventPlatz').value,besteRunde:document.getElementById('eventBesteRunde').value,runden:document.getElementById('eventRunden').value,quali:document.getElementById('eventQuali').value,reifen:document.getElementById('eventReifen').value,getriebe:document.getElementById('eventGetriebe').value,gewicht:document.getElementById('eventGewicht').value,kommentare:document.getElementById('eventKommentare').value};if(id)rsDb.events[rsDb.events.findIndex(x=>x.id===id)]=d;else rsDb.events.push(d);saveDatabase();renderEventsList();document.getElementById('eventsModal').style.display='none';};
    const mf = document.getElementById('motorenForm'); if(mf) mf.onsubmit=(e)=>{e.preventDefault();const id=document.getElementById('motorIdInput').value;const d={id:id||`motor_${Date.now()}`,name:document.getElementById('motorName').value,klasse:document.getElementById('motorKlasse').value,hersteller:document.getElementById('motorHersteller').value,rpm:document.getElementById('motorRpm').value,maxRpm:document.getElementById('motorMaxRpm').value,rennen:document.getElementById('motorRennen').value,status:document.getElementById('motorStatus').value,notizen:document.getElementById('motorNotizen').value};if(id)rsDb.motoren[rsDb.motoren.findIndex(x=>x.id===id)]=d;else rsDb.motoren.push(d);saveDatabase();renderMotorenList();document.getElementById('motorenModal').style.display='none';};
    const af = document.getElementById('autosForm'); if(af) af.onsubmit=(e)=>{e.preventDefault();const id=document.getElementById('autoIdInput').value;const d={id:id||`auto_${Date.now()}`,klasse:document.getElementById('autoKlasse').value,chassis:document.getElementById('autoChassis').value,karosserie:document.getElementById('autoKarosserie').value,federn:document.getElementById('autoFedern').value,wackel:document.getElementById('autoWackel').value,gewichtsver:document.getElementById('autoGewichtsver').value,kugellager:document.getElementById('autoKugellager').value,hoehe:document.getElementById('autoHoehe').value,reifen:document.getElementById('autoReifen').value,motor:document.getElementById('autoMotor').value,zahnrad:document.getElementById('autoZahnrad').value,kommentare:document.getElementById('autoKommentare').value};if(id)rsDb.autos[rsDb.autos.findIndex(x=>x.id===id)]=d;else rsDb.autos.push(d);saveDatabase();renderAutosList();document.getElementById('autosModal').style.display='none';};
    const sf = document.getElementById('streckenForm'); if(sf) sf.onsubmit=(e)=>{e.preventDefault();const id=document.getElementById('streckeIdInput').value;const d={id:id||`strecke_${Date.now()}`,name:document.getElementById('streckeName').value,ort:document.getElementById('streckeOrt').value,laenge:document.getElementById('streckeLaenge').value,typ:document.getElementById('streckeTyp').value,spannung:document.getElementById('streckeSpannung').value,rekord:document.getElementById('streckeRekord').value,rollout:document.getElementById('streckeRollout').value,notizen:document.getElementById('streckeNotizen').value};if(id)rsDb.strecken[rsDb.strecken.findIndex(x=>x.id===id)]=d;else rsDb.strecken.push(d);saveDatabase();renderStreckenList();document.getElementById('streckenModal').style.display='none';};
});